//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRDecemberAflyatunov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int id { get; set; }
        public Nullable<int> idStudent { get; set; }
        public Nullable<int> idGroupSubject { get; set; }
        public Nullable<int> ModuleScore { get; set; }
        public Nullable<int> FinalGrade { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> UpdatedByTeacher { get; set; }
    
        public virtual GroupSubjects GroupSubjects { get; set; }
        public virtual Students Students { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
