//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRDecemberAflyatunov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupSubjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupSubjects()
        {
            this.Grades = new HashSet<Grades>();
        }
    
        public int id { get; set; }
        public Nullable<int> idGroup { get; set; }
        public Nullable<int> idSubject { get; set; }
        public Nullable<int> idTeacher { get; set; }
        public Nullable<int> Semester { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<bool> isCurrent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grades> Grades { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
